# Generated by Django 3.0.5 on 2021-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(default='', max_length=256)),
                ('state', models.CharField(default='', max_length=256)),
                ('village', models.CharField(default='', max_length=256)),
                ('zone', models.CharField(default='', max_length=256)),
                ('price', models.IntegerField(default=0)),
                ('area', models.IntegerField(default=0)),
                ('contract', models.CharField(default='Sale', max_length=256)),
                ('type', models.CharField(default='', max_length=256)),
                ('source', models.CharField(default='', max_length=256)),
                ('year', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
