# Generated by Django 3.0.5 on 2021-03-15 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', max_length=256)),
                ('user_name', models.CharField(default='', max_length=256)),
                ('user_user_name', models.CharField(default='', max_length=256)),
                ('user_email', models.CharField(default='', max_length=256)),
                ('user_phone', models.CharField(default='', max_length=256)),
                ('user_pass', models.CharField(default='', max_length=256)),
            ],
        ),
    ]
